shell = "zsh"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.compinit]
inline = 'autoload -Uz compinit && compinit -d "${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompdump"'

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

# Must come after syntax highlighting.
[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
