window:
  # dimensions:
  #   columns: 100
  #   lines: 36

  # position:
  #   x: 1050
  #   y: 250

  # padding:
  #     x: 10
  #     y: 10

  decorations: none
  opacity: 0.95
  startup_mode: Maximized

# colors:
#   # Default colors
#   primary:
#     background: '#202330'
#     foreground: '#fae8b6'

#   # Normal colors
#   normal:
#     black:   '#FAE8B6'
#     red:     '#ff38a2'
#     green:   '#9cd162'
#     yellow:  '#ffc85b'
#     blue:    '#eba4ac'
#     magenta: '#d9bcef'
#     cyan:    '#87c095'
#     white:   '#fff0f5'

#   # Bright colors
#   bright:
#     black:   '#FAE8B6'
#     red:     '#ff38a2'
#     green:   '#9cd162'
#     yellow:  '#ffc85b'
#     blue:    '#eba4ac'
#     magenta: '#d9bcef'
#     cyan:    '#87c095'
#     white:   '#fff0f5'

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: "#11121D"
    foreground: "#a0A8CD"
  normal:
    black: "#32344a"
    red: "#f7768e"
    green: "#9ece6a"
    yellow: "#e0af68"
    blue: "#7aa2f7"
    magenta: "#ad8ee6"
    cyan: "#449dab"
    white: "#787c99"
  bright:
    black: "#444b6a"
    red: "#ff7a93"
    green: "#b9f27c"
    yellow: "#ff9e64"
    blue: "#7da6ff"
    magenta: "#bb9af7"
    cyan: "#0db9d7"
    white: "#acb0d0"

font:
  size: 15
  normal:
    family: 'CaskaydiaCove Nerd Font'
    style: Regular
  bold:
    family: 'CaskaydiaCove Nerd Font'
    style: Bold
  italic:
    family: 'CaskaydiaCove Nerd Font'
    style: Italic
  bold_italic:
    family: 'CaskaydiaCove Nerd Font'
    style: Bold Italic
