#!/usr/bin/env sh

yabai -m config                                 \
    layout                       bsp            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                on             \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    window_border                off            \
    window_border_width          6              \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    split_ratio                  0.50           \
    auto_balance                 off            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \
                                                \
    top_padding                  10             \
    bottom_padding               10             \
    left_padding                 10             \
    right_padding                10             \
    window_gap                   06
    # external_bar all:30:0

# NOTE: not work System Information & System Preferences

# yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
# yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

yabai -m rule --add app='^Finder$' manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app='^System Settings$' manage=off
yabai -m rule --add app='^Spotify$' manage=off
yabai -m rule --add app='^Discord$' manage=off
yabai -m rule --add app='^DeepL$' manage=off
yabai -m rule --add app='^Digital Color Meter$' manage=off

# yabai -m config layout bsp

echo "yabai configuration loaded.."
