run-shell "bash ~/.config/tmux/scripts/reset-default-keys.sh"
source-file "~/.config/tmux/conf/base.conf"
source-file "~/.config/tmux/conf/bindings.conf"
source-file "~/.config/tmux/conf/plugins.conf"
