name: chezmoi verify (macOS)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  verify-macos:
    runs-on: macos-latest

    env:
      CHEZMOI_SOURCE_DIR: ${{ github.workspace }}

    steps:
      # 1. ソースを取得
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. chezmoi 本体をインストール
      - name: Install chezmoi
        run: |
          curl -fsLS get.chezmoi.io | bash -s -- -b "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      # 3. 仮想 HOME に dotfiles を展開
      - name: Generate target state (no scripts)
        run: |
          mkdir -p /tmp/cheztest
          chezmoi init --destination=/tmp/cheztest \
                       --no-tty --apply \
                       --exclude=scripts

      # 4. 検証：差分が無ければ exit 0
      - name: Verify target == actual
        run: |
          chezmoi verify \
            --destination=/tmp/cheztest \
            --exclude=scripts

      # 5. run スクリプト付きで apply（brew の実行を許可）
      - name: Apply with scripts (dry)
        env:
          BREW_FLAGS: --dry-run
        run: |
          mkdir -p /tmp/cheztest
          chezmoi apply \
            --destination=/tmp/cheztest \
            --no-tty \
