name: macos
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run brew bundle
        run: brew bundle

      - name: Run install.sh
        run: ${GITHUB_WORKSPACE}install.sh
